// <auto-generated />
using CIS470_TeamE_CourseProject_23Jan18.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CIS470_TeamE_CourseProject_23Jan18.Migrations
{
    [DbContext(typeof(CIS470_TeamE_CourseProject_23Jan18Context))]
    partial class CIS470_TeamE_CourseProject_23Jan18ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS470_TeamE_CourseProject_23Jan18.Models.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("designRequest");

                    b.Property<DateTime>("insertedDateTime");

                    b.Property<string>("jobType");

                    b.Property<DateTime>("lastUpdated");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<int>("mediaCatalogNumber");

                    b.Property<string>("mediaType");

                    b.Property<string>("orderStatus");

                    b.HasKey("orderID");

                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
